package cn.bstar.gale.boss.model;

// default package
// Generated 2011-12-22 9:41:03 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Domain generated by hbm2java
 */
public class Domain implements java.io.Serializable {

	private long domainId;
	private Domain domain;
	private String name;
	private String description;
	private Long domainDepth;
	private Byte isLeaf;
	private Byte isOccupied;
	private Set<Domain> domains = new HashSet<Domain>(0);
	private ServerManageInfo serverManageInfo;

	public Domain() {
	}

	public Domain(long domainId) {
		this.domainId = domainId;
	}

	public long getDomainId() {
		return this.domainId;
	}

	public void setDomainId(long domainId) {
		this.domainId = domainId;
	}

	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getDomainDepth() {
		return this.domainDepth;
	}

	public void setDomainDepth(Long domainDepth) {
		this.domainDepth = domainDepth;
	}

	public Byte getIsLeaf() {
		return this.isLeaf;
	}

	public void setIsLeaf(Byte isLeaf) {
		this.isLeaf = isLeaf;
	}

	public Set<Domain> getDomains() {
		return this.domains;
	}

	public void setDomains(Set<Domain> domains) {
		this.domains = domains;
	}

	public ServerManageInfo getServerManageInfo() {
		return serverManageInfo;
	}

	public void setServerManageInfo(ServerManageInfo serverManageInfo) {
		this.serverManageInfo = serverManageInfo;
	}

	public Byte getIsOccupied() {
		return isOccupied;
	}

	public void setIsOccupied(Byte isOccupied) {
		this.isOccupied = isOccupied;
	}

}
