package cn.bstar.gale.boss.model;

// default package
// Generated 2011-12-22 9:41:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OsInfo generated by hbm2java
 */
public class OsInfo implements java.io.Serializable {

	private long osId;
	private ServerManageInfo serverManageInfo;
	private String ipAddress1;
	private Byte isVm;
	private String osName;
	private String osVersion;
	private String osBit;
	private Byte osStatu;
	private String osUser;
	private String osPasswd;
	private String ipAddress2;
	private String ipAddress3;
	private String ipAddress4;
	private Date dataCreated;
	private Long createdBy;
	private Date dateModified;
	private Long modifiedBy;
	private String memo;
	private String manageName;
	private String snmpUser;
	private String snmpPasswd;
	private Float cupUserate;
	private Float memUserate;
	private Float hdUserate;
	private String sysUptime;
	private String sysProcesses;

	public OsInfo() {
	}

	public OsInfo(long osId) {
		this.osId = osId;
	}

	public OsInfo(long osId, ServerManageInfo serverManageInfo,
			String ipAddress1, Byte isVm, String osName, String osVersion,
			String osBit, Byte osStatu, String osUser, String osPasswd,
			String ipAddress2, String ipAddress3, String ipAddress4,
			Date dataCreated, Long createdBy, Date dateModified,
			Long modifiedBy, String memo, String manageName, String snmpUser,
			String snmpPasswd) {
		this.osId = osId;
		this.serverManageInfo = serverManageInfo;
		this.ipAddress1 = ipAddress1;
		this.isVm = isVm;
		this.osName = osName;
		this.osVersion = osVersion;
		this.osBit = osBit;
		this.osStatu = osStatu;
		this.osUser = osUser;
		this.osPasswd = osPasswd;
		this.ipAddress2 = ipAddress2;
		this.ipAddress3 = ipAddress3;
		this.ipAddress4 = ipAddress4;
		this.dataCreated = dataCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.memo = memo;
		this.manageName = manageName;
		this.snmpUser = snmpUser;
		this.snmpPasswd = snmpPasswd;
	}

	public long getOsId() {
		return this.osId;
	}

	
	
	public String getSysUptime() {
		return sysUptime;
	}

	public void setSysUptime(String sysUptime) {
		this.sysUptime = sysUptime;
	}

	public String getSysProcesses() {
		return sysProcesses;
	}

	public void setSysProcesses(String sysProcesses) {
		this.sysProcesses = sysProcesses;
	}

	public Float getCupUserate() {
		return cupUserate;
	}

	public void setCupUserate(Float cupUserate) {
		this.cupUserate = cupUserate;
	}

	public Float getMemUserate() {
		return memUserate;
	}

	public void setMemUserate(Float memUserate) {
		this.memUserate = memUserate;
	}

	public Float getHdUserate() {
		return hdUserate;
	}

	public void setHdUserate(Float hdUserate) {
		this.hdUserate = hdUserate;
	}

	public void setOsId(long osId) {
		this.osId = osId;
	}

	public ServerManageInfo getServerManageInfo() {
		return this.serverManageInfo;
	}

	public void setServerManageInfo(ServerManageInfo serverManageInfo) {
		this.serverManageInfo = serverManageInfo;
	}

	public String getIpAddress1() {
		return this.ipAddress1;
	}

	public void setIpAddress1(String ipAddress1) {
		this.ipAddress1 = ipAddress1;
	}

	public Byte getIsVm() {
		return this.isVm;
	}

	public void setIsVm(Byte isVm) {
		this.isVm = isVm;
	}

	public String getOsName() {
		return this.osName;
	}

	public void setOsName(String osName) {
		this.osName = osName;
	}

	public String getOsVersion() {
		return this.osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	public String getOsBit() {
		return this.osBit;
	}

	public void setOsBit(String osBit) {
		this.osBit = osBit;
	}

	public Byte getOsStatu() {
		return this.osStatu;
	}

	public void setOsStatu(Byte osStatu) {
		this.osStatu = osStatu;
	}

	public String getOsUser() {
		return this.osUser;
	}

	public void setOsUser(String osUser) {
		this.osUser = osUser;
	}

	public String getOsPasswd() {
		return this.osPasswd;
	}

	public void setOsPasswd(String osPasswd) {
		this.osPasswd = osPasswd;
	}

	public String getIpAddress2() {
		return this.ipAddress2;
	}

	public void setIpAddress2(String ipAddress2) {
		this.ipAddress2 = ipAddress2;
	}

	public String getIpAddress3() {
		return this.ipAddress3;
	}

	public void setIpAddress3(String ipAddress3) {
		this.ipAddress3 = ipAddress3;
	}

	public String getIpAddress4() {
		return this.ipAddress4;
	}

	public void setIpAddress4(String ipAddress4) {
		this.ipAddress4 = ipAddress4;
	}

	public Date getDataCreated() {
		return this.dataCreated;
	}

	public void setDataCreated(Date dataCreated) {
		this.dataCreated = dataCreated;
	}

	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getManageName() {
		return this.manageName;
	}

	public void setManageName(String manageName) {
		this.manageName = manageName;
	}

	public String getSnmpUser() {
		return this.snmpUser;
	}

	public void setSnmpUser(String snmpUser) {
		this.snmpUser = snmpUser;
	}

	public String getSnmpPasswd() {
		return this.snmpPasswd;
	}

	public void setSnmpPasswd(String snmpPasswd) {
		this.snmpPasswd = snmpPasswd;
	}

}
